# Generated by Django 4.2 on 2026-05-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='fine_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('issue_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='transactions.issuebook')),
            ],
        ),
    ]
